In [1]:
#from google.colab import drive 
#drive.mount('/content/gdrive',force_remount=True)

In [2]:
import pandas as pd 
import numpy as np
df=pd.read_csv("weatheraus.csv")


In [3]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [4]:
features=['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed',
          'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow']
features1=['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed',
          'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Temp9am',
       'Temp3pm', 'RainToday']

In [5]:
def strto(a):
    if a=='Yes':
        return 1
    else:
        return 0

In [6]:
df=df[features]
df['RainToday']=df['RainToday'].apply(strto)
df['RainTomorrow']=df['RainTomorrow'].apply(strto)

In [7]:
df=df.head(500)

In [8]:
df

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
0       13.4     22.9       0.6           44.0          20.0          24.0   
1        7.4     25.1       0.0           44.0           4.0          22.0   
2       12.9     25.7       0.0           46.0          19.0          26.0   
3        9.2     28.0       0.0           24.0          11.0           9.0   
4       17.5     32.3       1.0           41.0           7.0          20.0   
..       ...      ...       ...            ...           ...           ...   
495     10.1     25.1       0.0           17.0           0.0           9.0   
496     11.2     25.9       0.0           17.0           0.0           9.0   
497     11.8     25.2       0.0           26.0           2.0          13.0   
498     12.3     27.5       0.0           20.0           6.0           7.0   
499     11.4     27.3       0.0           17.0           0.0           9.0   

     Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Temp9am  Temp3pm  \
0           71.0         22.0       1007.7       1007.1     16.9     21.8   
1           44.0         25.0       1010.6       1007.8     17.2     24.3   
2           38.0         30.0       1007.6       1008.7     21.0     23.2   
3           45.0         16.0       1017.6       1012.8     18.1     26.5   
4           82.0         33.0       1010.8       1006.0     17.8     29.7   
..           ...          ...          ...          ...      ...      ...   
495         67.0         47.0       1027.1       1023.2     16.8     24.6   
496         81.0         46.0       1025.7       1021.9     14.6     25.6   
497         79.0         49.0       1024.6       1020.1     16.4     24.3   
498         74.0         44.0       1022.8       1019.5     18.5     26.4   
499         74.0         40.0       1023.6       1019.4     17.8     26.4   

     RainToday  RainTomorrow  
0            0             0  
1            0             0  
2            0             0  
3            0             0  
4            0             0  
..         ...           ...  
495          0             0  
496          0             0  
497          0             0  
498          0             0  
499          0             0  

[500 rows x 14 columns]

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df=df.dropna()

In [11]:
df_features = df[features1]

df_target = df['RainTomorrow']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_features, np.ravel(df_target), test_size=0.30, random_state=101)

In [12]:
from sklearn.svm import SVC
model = SVC()

#Train the model using fit method
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
predictions = model.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test, predictions))

[[110   0]
 [ 36   0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86       110
           1       0.00      0.00      0.00        36

    accuracy                           0.75       146
   macro avg       0.38      0.50      0.43       146
weighted avg       0.57      0.75      0.65       146



C:\Users\Admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
param_grid = {'C':[0.1, 1, 10, 100, 1000], 'gamma':[1, 0.1, 0.01, 0.001, 0.0001]}
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(), param_grid, verbose=3)

In [15]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.824, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.824, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.809, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.809, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.821, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.824, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ..........

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s



[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.809, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.809, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.821, total=   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................... C=0.1, gamma=0.01, score=0.824, total=   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................... C=0.1, gamma=0.01, score=0.824, total=   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................... C=0.1, gamma=0.01, score=0.809, total=   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................... C=0.1, gamma=0.01, score=0.809, total=   0.0s
[CV] 

[CV] .................... C=10, gamma=0.01, score=0.821, total=   0.0s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.882, total=   0.0s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.868, total=   0.0s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.941, total=   0.0s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.882, total=   0.0s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.896, total=   0.0s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.912, total=   0.0s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:    1.3s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [16]:
print('The best parameters are ', grid.best_params_)

The best parameters are  {'C': 10, 'gamma': 0.0001}


In [17]:
grid_predictions=grid.predict(X_test)

In [18]:
print(confusion_matrix(y_test,grid_predictions))
print('\n')
print(classification_report(y_test, grid_predictions))

[[105   5]
 [ 18  18]]


              precision    recall  f1-score   support

           0       0.85      0.95      0.90       110
           1       0.78      0.50      0.61        36

    accuracy                           0.84       146
   macro avg       0.82      0.73      0.76       146
weighted avg       0.84      0.84      0.83       146



### On the Whole Dataset

In [21]:
df1=pd.read_csv("weatheraus.csv")

In [22]:
df1=df1[features]
df1['RainToday']=df1['RainToday'].apply(strto)
df1['RainTomorrow']=df1['RainTomorrow'].apply(strto)

In [23]:
df1=df1.dropna()

In [24]:
df1

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
0          13.4     22.9       0.6           44.0          20.0          24.0   
1           7.4     25.1       0.0           44.0           4.0          22.0   
2          12.9     25.7       0.0           46.0          19.0          26.0   
3           9.2     28.0       0.0           24.0          11.0           9.0   
4          17.5     32.3       1.0           41.0           7.0          20.0   
...         ...      ...       ...            ...           ...           ...   
142188      3.5     21.8       0.0           31.0          15.0          13.0   
142189      2.8     23.4       0.0           31.0          13.0          11.0   
142190      3.6     25.3       0.0           22.0          13.0           9.0   
142191      5.4     26.9       0.0           37.0           9.0           9.0   
142192      7.8     27.0       0.0           28.0          13.0           7.0   

        Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Temp9am  Temp3pm  \
0              71.0         22.0       1007.7       1007.1     16.9     21.8   
1              44.0         25.0       1010.6       1007.8     17.2     24.3   
2              38.0         30.0       1007.6       1008.7     21.0     23.2   
3              45.0         16.0       1017.6       1012.8     18.1     26.5   
4              82.0         33.0       1010.8       1006.0     17.8     29.7   
...             ...          ...          ...          ...      ...      ...   
142188         59.0         27.0       1024.7       1021.2      9.4     20.9   
142189         51.0         24.0       1024.6       1020.3     10.1     22.4   
142190         56.0         21.0       1023.5       1019.1     10.9     24.5   
142191         53.0         24.0       1021.0       1016.8     12.5     26.1   
142192         51.0         24.0       1019.4       1016.5     15.1     26.0   

        RainToday  RainTomorrow  
0               0             0  
1               0             0  
2               0             0  
3               0             0  
4               0             0  
...           ...           ...  
142188          0             0  
142189          0             0  
142190          0             0  
142191          0             0  
142192          0             0  

[119590 rows x 14 columns]

In [25]:
df_target1 = df1['RainTomorrow']
df_features1 = df1[features1]
X_train1, X_test1, y_train1, y_test1 = train_test_split(df_features1, np.ravel(df_target1), test_size=0.30, random_state=101)

In [26]:
gridpred=grid.predict(X_train1)

In [27]:
print(confusion_matrix(y_train1,gridpred))
print('\n')
print(classification_report(y_train1, gridpred))

[[56455  9010]
 [ 6053 12195]]


              precision    recall  f1-score   support

           0       0.90      0.86      0.88     65465
           1       0.58      0.67      0.62     18248

    accuracy                           0.82     83713
   macro avg       0.74      0.77      0.75     83713
weighted avg       0.83      0.82      0.82     83713

